import React from 'react';
import { Router } from 'react-router';
import { createBrowserHistory } from 'history';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import { createStore } from 'redux';
import reducer from './reducers';
import App from './routes/App';

const initialState = {
  users: [
    {
      idUser: 1,
      documentType: 'Cedula de Extranjeria',
      cedulaId: '240.157.211',
      name: 'Ibrahim',
      lastname: 'Criple',
      email: 'icriple0@devhub.com',
      phone: '850-991-2535',
      cellphone: '253-834-9133',
      state: 'Active',
      role: 'Medico',
    },
    {
      idUser: 2,
      documentType: 'Pasaporte',
      cedulaId: '205.203.119',
      name: 'Kial',
      lastname: 'Mathivat',
      email: 'kmathivatc@buzzfeed.com',
      phone: '244-699-7820',
      cellphone: '889-952-3786',
      state: 'Active',
      role: 'Paciente',
    },
    {
      idUser: 3,
      documentType: 'Cedula de Ciudadania',
      cedulaId: '160.350.170',
      name: 'Alan',
      lastname: 'Ferrieri',
      email: 'aferrieri2@comsenz.com',
      phone: '924-370-3585',
      cellphone: '251-988-6656',
      state: 'Active',
      role: 'Medico',
    },
    {
      idUser: 4,
      documentType: 'Cedula de Extranjeria',
      cedulaId: '122.107.148',
      name: 'Cindelyn',
      lastname: 'Birkenshaw',
      email: 'cbirkenshawg@google.com.hk',
      phone: '445-407-6809',
      cellphone: '729-496-3676',
      state: 'Desactive',
      role: 'Paciente',
    },
    {
      idUser: 5,
      documentType: 'Pasaporte',
      cedulaId: '32.230.118',
      name: 'Darb',
      lastname: 'Eaken',
      email: 'deaken4@tinypic.com',
      phone: '945-194-1878',
      cellphone: '793-592-1980',
      state: 'Active',
      role: 'Medico',
    },
    {
      idUser: 6,
      documentType: 'Cedula de Ciudadania',
      cedulaId: '109.580.227',
      name: 'Rora',
      lastname: 'Elders',
      email: 'relders5@xinhuanet.com',
      phone: '269-235-4603',
      cellphone: '210-251-2746',
      state: 'Active',
      role: 'Medico',
    },
    {
      idUser: 7,
      documentType: 'Cedula de Ciudadania',
      cedulaId: '4.174.116',
      name: 'Carina',
      lastname: 'Grimm',
      email: 'cgrimma@infoseek.co.jp',
      phone: '120-606-1718',
      cellphone: '457-403-6740',
      state: 'Desactive',
      role: 'Paciente',
    },
    {
      idUser: 8,
      documentType: 'Cedula de Ciudadania',
      cedulaId: '154.204.215',
      name: 'Tessy',
      lastname: 'Summerson',
      email: 'tsummerson7@about.com',
      phone: '199-330-7491',
      cellphone: '981-247-5274',
      state: 'Active',
      role: 'Administrador',
    },
    {
      idUser: 9,
      documentType: 'Cedula de Extranjeria',
      cedulaId: '236.243.782',
      name: 'Ellissa',
      lastname: 'Lambillion',
      email: 'elambillion8@jugem.jp',
      phone: '455-748-3334',
      cellphone: '990-912-9978',
      state: 'Active',
      role: 'Administrador',
    },
    {
      idUser: 10,
      documentType: 'Pasaporte',
      cedulaId: '125.370.226',
      name: 'Riki',
      lastname: 'Mewton',
      email: 'rmewton6@meetup.com',
      phone: '605-148-8940',
      cellphone: '911-579-5799',
      state: 'Active',
      role: 'Administrador',
    },
    {
      idUser: 11,
      documentType: 'Cedula de Ciudadania',
      cedulaId: '201.123.160',
      name: 'Arleta',
      lastname: 'McNirlan',
      email: 'amcnirlanb@utexas.edu',
      phone: '892-211-3864',
      cellphone: '918-387-1153',
      state: 'Desactive',
      role: 'Paciente',
    },
    {
      idUser: 12,
      documentType: 'Cedula de Ciudadania',
      cedulaId: '68.230.124',
      name: 'Luca',
      lastname: 'Owenson',
      email: 'lowenson3@columbia.edu',
      phone: '859-829-7946',
      cellphone: '107-595-1374',
      state: 'Active',
      role: 'Medico',
    },
    {
      idUser: 13,
      documentType: 'Cedula de Ciudadania',
      cedulaId: '139.158.253',
      name: 'Lory',
      lastname: 'Burgane',
      email: 'lburganej@alexa.com',
      phone: '222-426-4961',
      cellphone: '982-570-8813',
      state: 'Active',
      role: 'Paciente',
    },
    {
      idUser: 14,
      documentType: 'Cedula de Ciudadania',
      cedulaId: '215.240.100',
      name: 'Brennen',
      lastname: 'Selwin',
      email: 'bselwind@kickstarter.com',
      phone: '830-219-4839',
      cellphone: '520-426-1294',
      state: 'Active',
      role: 'Paciente',
    },
    {
      idUser: 15,
      documentType: 'Pasaporte',
      cedulaId: '130.118.582',
      name: 'Robina',
      lastname: 'Carder',
      email: 'rcarder1@google.com.au',
      phone: '734-760-7304',
      cellphone: '470-888-3025',
      state: 'Active',
      role: 'Medico',
    },
    {
      idUser: 16,
      documentType: 'Cedula de Ciudadania',
      cedulaId: '247.193.177',
      name: 'Ches',
      lastname: 'Padula',
      email: 'cpadulaf@newyorker.com',
      phone: '370-968-0734',
      cellphone: '734-879-9493',
      state: 'Active',
      role: 'Paciente',
    },
    {
      idUser: 17,
      documentType: 'Pasaporte',
      cedulaId: '238.141.198',
      name: 'Bridgette',
      lastname: 'Hazelden',
      email: 'bhazeldenh@slate.com',
      phone: '206-898-3278',
      cellphone: '314-458-6951',
      state: 'Active',
      role: 'Paciente',
    },
    {
      idUser: 18,
      documentType: 'Cedula de Ciudadania',
      cedulaId: '95.230.212',
      name: 'Ajay',
      lastname: 'Gilvary',
      email: 'agilvary9@intel.com',
      phone: '782-967-0259',
      cellphone: '713-679-0683',
      state: 'Desactive',
      role: 'Paciente',
    },
    {
      idUser: 19,
      documentType: 'Cedula de Ciudadania',
      cedulaId: '121.921.992',
      name: 'Bartholomeus',
      lastname: 'Hollingdale',
      email: 'bhollingdalei@hp.com',
      phone: '203-968-2229',
      cellphone: '931-761-4768',
      state: 'Active',
      role: 'Paciente',
    },
    {
      idUser: 20,
      documentType: 'Cedula de Extranjeria',
      cedulaId: '215.110.177',
      name: 'Corrianne',
      lastname: 'Bollini',
      email: 'cbollinie@freewebs.com',
      phone: '144-125-4770',
      cellphone: '148-950-2216',
      state: 'Active',
      role: 'Paciente',
    },
  ],
};

const store = createStore(reducer, initialState);
const history = createBrowserHistory();

ReactDOM.render(
  <Provider store={store}>
    <Router history={history}>
      <App />
    </Router>
  </Provider>,
  document.getElementById('app')
);
